<?php

use Illuminate\Database\Seeder;
use LBHurtado\Ballot\Models\{Candidate, Position};

class CandidateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $positions_array = [
            [
                'position' => 'President',
                'candidates' => [
                    ['code' => 'BELLEZA',       'name' => 'BELLEZA, DARIN'],
                    ['code' => 'BAUTISTA-1',    'name' => 'BAUTISTA, TERRENCE'],
                    ['code' => 'BAUTISTA-2',    'name' => 'BAUTISTA, VIRGINIA'],
                    ['code' => 'BUENAFLOR',     'name' => 'BUENAFLOR, MARTIN'],
                    ['code' => 'NATIVIDAD',     'name' => 'NATIVIDAD, EVA'],
                    ['code' => 'ROBLES',        'name' => 'ROBLES, DENNIS'],
                ],
            ],
            [
                'position' => 'Vice-President',
                'candidates' => [
                    ['code' => 'ISIGANI',   'name' => 'ISIGANI, GENER'],
                    ['code' => 'JIMENEZ',   'name' => 'JIMENEZ, HOMOBONO'],
                    ['code' => 'RIVERA-1',  'name' => 'RIVERA, JOSELITO'],
                    ['code' => 'VILORIA',   'name' => 'VILORIA, MARY']
                ],
            ],
            [
                'position' => 'Senator',
                'candidates' => [
                    ['code' => 'ABEJO',    'name' => 'ABEJO, VANGIE'],
                    ['code' => 'AFUANG',    'name' => 'AFUANG, ABNER'],
                    ['code' => 'AGUILAR-1', 'name' => 'AGUILAR, FREDDIE'],
                    ['code' => 'ALBANI',    'name' => 'ALBANI, SHARIFF'],
                    ['code' => 'ALEJANO',    'name' => 'ALEJANO, GARY'],
                    ['code' => 'ALFAJORA',    'name' => 'ALFAJORA, RICHARD'],
                    ['code' => 'ALUNAN',    'name' => 'ALUNAN, RAFFY'],
                    ['code' => 'ANGARA',    'name' => 'ANGARA, EDGARDO SONNY'],
                    ['code' => 'AQUINO',    'name' => 'AQUINO, BENIGNO BAM'],
                    ['code' => 'ARCEGA',    'name' => 'ARCEGA, GERALD'],
                    ['code' => 'ARELLANO',    'name' => 'ARELLANO, ERNESTO'],
                    ['code' => 'ARIAS',    'name' => 'ARIAS, MARCELINO'],
                    ['code' => 'AUSTRIA',    'name' => 'AUSTRIA, BERNARD'],
                    ['code' => 'BALDEVARONA',    'name' => 'BALDEVARONA, BALDE'],
                    ['code' => 'BINAY',    'name' => 'BINAY, NANCY'],
                    ['code' => 'BONG REVILLA',    'name' => 'BONG REVILLA, RAMON JR'],
                    ['code' => 'CACERES',    'name' => 'CACERES, JESUS'],
                    ['code' => 'CASIÑO',    'name' => 'CASIÑO, TOTI'],
                    ['code' => 'CAYETANO',    'name' => 'CAYETANO, PIA'],
                    ['code' => 'CHAVEZ',    'name' => 'CHAVEZ, MELCHOR'],
                    ['code' => 'CHONG',    'name' => 'CHONG, GLENN'],
                    ['code' => 'COLMENARES',    'name' => 'COLMENARES, NERI'],
                    ['code' => 'DE GUZMAN',    'name' => 'DE GUZMAN, KA LEODY'],
                    ['code' => 'DELA ROSA',    'name' => 'DELA ROSA, BATO'],
                    ['code' => 'DIOKNO',    'name' => 'DIOKNO, CHEL'],
                    ['code' => 'EJERCITO',    'name' => 'EJERCITO, ESTRADA JV'],
                    ['code' => 'ENRILE',    'name' => 'ENRILE, JUAN PONCE'],
                    ['code' => 'ESCUDERO',    'name' => 'ESCUDERO, AGNES'],
                    ['code' => 'ESTRADA',    'name' => 'ESTRADA, JINGGOY'],
                    ['code' => 'FRANCISCO',    'name' => 'FRANCISCO, ELMER'],
                    ['code' => 'GADDI',    'name' => 'GADDI, CHARLIE'],
                    ['code' => 'GADON',    'name' => 'GADON, LARRY'],
                    ['code' => 'GENEROSO',    'name' => 'GENEROSO, GEN PEDERALISMO'],
                    ['code' => 'GO',    'name' => 'GO, BONG GO'],
                    ['code' => 'GUIGAYUMA',    'name' => 'GUIGAYUMA, JUNBERT'],
                    ['code' => 'GUTOC',    'name' => 'GUTOC, SAMIRA'],
                    ['code' => 'HILBAY',    'name' => 'HILBAY, PILO'],
                    ['code' => 'JANGAO',    'name' => 'JANGAO, BFG ABRAHAM'],
                    ['code' => 'JAVELLANA',    'name' => 'JAVELLANA, RJ'],
                    ['code' => 'LAPID',    'name' => 'LAPID, LITO'],
                    ['code' => 'MACALINTAL',    'name' => 'MACALINTAL, MACAROMY'],
                    ['code' => 'MALLILLIN',    'name' => 'MALLILLIN, EMILY'],
                    ['code' => 'MANGONDATO',    'name' => 'MANGONDATO, FAISAL'],
                    ['code' => 'MANGUDADATU',    'name' => 'MANGUDADATU, DONG'],
                    ['code' => 'MANICAD',    'name' => 'MANICAD, JIGGY'],
                    ['code' => 'MARCOS',    'name' => 'MARCOS, IMEE'],
                    ['code' => 'MATULA',    'name' => 'MATULA, JOSE SONNY'],
                    ['code' => 'MENIANO',    'name' => 'MENIANO, LUTHER'],
                    ['code' => 'MONTAÑO',    'name' => 'MONTAÑO, ALLAN'],
                    ['code' => 'NALLIW',    'name' => 'NALLIW, JOAN SHEELAH'],
                    ['code' => 'ONG-1',    'name' => 'ONG, DOC WILLIE'],
                    ['code' => 'OSMEÑA',    'name' => 'OSMEÑA, SERGE'],
                    ['code' => 'PADILLA',    'name' => 'PADILLA, DADO'],
                    ['code' => 'PIMENTEL',    'name' => 'PIMENTEL, KOKO'],
                    ['code' => 'POE',    'name' => 'POE, GRACE'],
                    ['code' => 'ROLEDA',    'name' => 'ROLEDA, DAN KAIBIGAN'],
                    ['code' => 'ROXAS',    'name' => 'ROXAS, MAR'],
                    ['code' => 'SAHIDULLA',    'name' => 'SAHIDULLA, LADY ANN'],
                    ['code' => 'TAÑADA',    'name' => 'TAÑADA, LORENZO ERIN TAPAT'],
                    ['code' => 'TOLENTINO',    'name' => 'TOLENTINO, FRANCIS'],
                    ['code' => 'VALDES',    'name' => 'VALDES, BUTCH'],
                    ['code' => 'VILLAR',    'name' => 'VILLAR, CYNTHIA'],
                ],

            ],
            [
                'position' => 'Party-List Representative',
                'candidates' => [
                    ['code' => 'PL -1',    'name' => '(001) BAYAN MUNA – BAYAN MUNA'],
                    ['code' => 'PL -2',    'name' => '(002) KABAYAN – KABALIKAT NG MAMAMAYAN'],
                    ['code' => 'PL -3',    'name' => '(003) MAGSASAKA – MAGKAKASAMA SA SAKAHAN, KAUNLARAN'],
                    ['code' => 'PL -4',    'name' => '(004) PEACE – PHILIPPINE EDUCATORS ALLIANCE FOR COMMUNITY EMPOWERMENT'],
                    ['code' => 'PL -6',    'name' => '(006) KONTRA BROWNOUT PARTYLIST – NATIONAL ASSOCIATION FOR ELECTRICITY CONSUMERS FOR REFORMS, INC'],
                    ['code' => 'PL -7',    'name' => '(007) OFW FAMILY – OFW FAMILY CLUB, INC'],
                    ['code' => 'PL -8',    'name' => '(008) 1-UTAK – 1-UNITED TRANSPORT KOALISYON'],
                    ['code' => 'PL -9',    'name' => '(009) KUSUG TAUSUG – KUSUG TAUSUG'],
                    ['code' => 'PL -10',    'name' => '(010) GLOBAL – GLOBAL WORKERS AND FAMILY FEDERATION, INC.'],
                    ['code' => 'PL -12',    'name' => '(012) ANG NARS – ANG NARS, INC.'],
                    ['code' => 'PL -14',    'name' => '(014) ANAKPAWIS – ANAKPAWIS'],
                    ['code' => 'PL -16',    'name' => '(016) CWS – CONSTRUCTION WORKERS’ SOLIDARITY'],
                    ['code' => 'PL -17',    'name' => '(017) PTA –  PARENTS TEACHERS ALLIANCE'],
                    ['code' => 'PL -18',    'name' => '(018) RAM – Rebolusyonaryong Alyansang Makabansa'],
                    ['code' => 'PL -20',    'name' => '(020) DUMPER PTDA – DUMPER PHILIPPINES TAXI DRIVERS ASSOCIATION, INC.'],
                    ['code' => 'PL -21',    'name' => '(021) LUNTIAN – LUNTIANG PILIPINAS PARTYLIST'],
                    ['code' => 'PL -22',    'name' => '(022) AKO BISDAK – AKO BISDAK-BISAYANG DAKO (AB-DB), INC.'],
                    ['code' => 'PL -23',    'name' => '(023) ASEAN – ACADEMICIANS, STUDENTS AND EDUCATORS ALLIANCE INC.'],
                    ['code' => 'PL -24',    'name' => '(024) APEC – ASSOCIATION OF PHILIPPINES ELECTRIC COOPERATIVES'],
                    ['code' => 'PL -26',    'name' => '(026) PBA – PUWERSA NG BAYANING ATLETA'],
                    ['code' => 'PL -27',    'name' => '(027) AMEPA OFW – AMEPA OFW ACCESS CENTER, INC.'],
                    ['code' => 'PL -29',    'name' => '(029) BAHAY – BAHAY PARA SA PAMILYANG PILIPINO, INC.'],
                    ['code' => 'PL -30',    'name' => '(030) PRAI – PHILIPPINE NATIONAL POLICE RETIREES ASSOCIATION, INC.'],
                    ['code' => 'PL -31',    'name' => '(031) JUAN MOVEMENT – JOINT UNION OF ACTIVE NATIONALIST FILIPINO MOVEMENT'],
                    ['code' => 'PL -32',    'name' => '(032) BUKLOD FILIPINO – PINAGBUKLOD NA FILIPINO PARA SA BAYAN'],
                    ['code' => 'PL -33',    'name' => '(033) CIBAC – CITIZENS’ BATTLE AGAINST CORRUPTION'],
                    ['code' => 'PL -35',    'name' => '(035) MURANG KURYENTE – MURANG KURYENTE PARTYLIST'],
                    ['code' => 'PL -36',    'name' => '(036) ANGKLA – ANGKLA: ANG PARTIDO NG MGA PILIPINONG MARINO, INC.'],
                    ['code' => 'PL -37',    'name' => '(037) GABRIELA – GABRIELA WOMEN’S APRTY'],
                    ['code' => 'PL -38',    'name' => '(038) AKO AN BISAYA – AKO AN BISAYA'],
                    ['code' => 'PL -39',    'name' => '(039) 1-LAMBAT – ISANG LAPIAN NG MANGINGISDA AT BAYAN TUNGO SA KAUNLARAN'],
                    ['code' => 'PL -42',    'name' => '(042) KABATAAN – KABATAAN PARTY LIST'],
                    ['code' => 'PL -43',    'name' => '(043) AN WARAY – AN WARAY'],
                    ['code' => 'PL -44',    'name' => '(044) SULONG DIGNIDAD – SULONG DIGNIDAD PARTY'],
                    ['code' => 'PL -46',    'name' => '(046) ALL-FISH – ALLIANCE OF PHILIPPINE FISHING FEDERATIONS, INC.'],
                    ['code' => 'PL -47',    'name' => '(047) ANAKLUSUGAN – ALAGAAN NATIN ATING KALUSUGAN'],
                    ['code' => 'PL -48',    'name' => '(048) TGP – TALINO AT GALING NG PINOY'],
                    ['code' => 'PL -49',    'name' => '(049) ABEKA – ABE KAPAMPANGAN (ABEKA) INC.'],
                    ['code' => 'PL -51',    'name' => '(051) AKMA-PTM – AKSYON MAGSASAKA-PARTIDO TINIG NG MASA (AKMA-PTM)'],
                    ['code' => 'PL -52',    'name' => '(052) ABS –ARTS BUSINESS AND SCIENCE PROFESSIONALS'],
                    ['code' => 'PL -53',    'name' => '(053) BH – BAGONG HENERASYON'],
                    ['code' => 'PL -54',    'name' => '(054) ANG PROBINSYANO – ALYANSA NG MGA MAMAMAYANG PROBINSYANO'],
                    ['code' => 'PL -55',    'name' => '(055) PM – PARTIDO MANGGAGAWA'],
                    ['code' => 'PL -58',    'name' => '(058) ANAC-IP – ANG NATIONAL COALITION OF INDIGENOUS PEOPLE ACTION NA! INC.'],
                    ['code' => 'PL -59',    'name' => '(059) SINAG – SINAG TUNGO SA KAUNLARAN'],
                    ['code' => 'PL -60',    'name' => '(060) PATROL – PUBLIC SAFETY ALLIANCE FOR TRANSFORMATION AND RULE OF LAW, INC.'],
                    ['code' => 'PL -63',    'name' => '(063) KOOP-KAMPI – KOOPERATIBA-KAPISANAN NG MAGSASAKA NG PILIPINAS'],
                    ['code' => 'PL -65',    'name' => '(065) UNIDO – UNION OF NATIONALISTIC DEMOCRATIC FILIPINO ORGANIZATION'],
                    ['code' => 'PL -67',    'name' => '(067) SBP – SERBISYO SA BAYAN APRTY'],
                    ['code' => 'PL -68',    'name' => '(068) PPP – PILIPINAS PARA SA PINOY'],
                    ['code' => 'PL -69',    'name' => '(069) INANG MAHAL – INA NA NAGMAMAHAL SA ANAK'],
                    ['code' => 'PL -71',    'name' => '(071) 1-ANG EDUKASYON – UNA ANG EDUKASYON'],
                    ['code' => 'PL -72',    'name' => '(072) KAMAIS – KAMAIS PILIPINAS (KAPATIRANG MAGMAMAIS NG PILIPINAS, INC.)'],
                    ['code' => 'PL -73',    'name' => '(073) ALIF – ANG LABAN NG INDIGINONG FILIPINO'],
                    ['code' => 'PL -74',    'name' => '(074) MATA – ANG MATA’Y ALAGAAN'],
                    ['code' => 'PL -75',    'name' => '(075) LPGMA – LPG MARKETERS ASSOCIATION INC.'],
                    ['code' => 'PL -76',    'name' => '(076) ABONO – ABONO'],
                    ['code' => 'PL -78',    'name' => '(078) AKO – AKO AYOKO SA BAWAL NA DROGA'],
                    ['code' => 'PL -79',    'name' => '(079) ABANTE PILIPINAS – AVID BUILDERS OF ACTIVE NATION’S CITIZENRY TOWARDS EMPOWERED PHILIPPINES'],
                    ['code' => 'PL -80',    'name' => '(080) MARINO – MARINO SAMAHAN NG MGA SEAMAN, INC.'],
                    ['code' => 'PL -82',    'name' => '(082) TAO MUNA – ANG TAO MUNA AT BAYAN'],
                    ['code' => 'PL -83',    'name' => '(083) ACT TEACHERS – ACT TEACHERS'],
                    ['code' => 'PL -84',    'name' => '(084) PEOPLE’S CHAMP – PEOPLE’S CHAMP GUARDIANS'],
                    ['code' => 'PL -86',    'name' => '(086) ALAY BUHAY – ALAY BUHAY COMMUNITY DEVELOPMENT FOUNDATION, INC.'],
                    ['code' => 'PL -87',    'name' => '(087) BUHAY – BUHAY HAYAAN YUMABONG'],
                    ['code' => 'PL -88',    'name' => '(088) AKBAYAN – AKBAYAN CITIZENS ACTION PARTY'],
                    ['code' => 'PL -89',    'name' => '(089) PARTIDO SANDUGO – PARTIDO SANDUGO'],
                    ['code' => 'PL -91',    'name' => '(091) PROBINSYANO AKO – PROBINSYANO AKO'],
                    ['code' => 'PL -92',    'name' => '(092) AKO BISAYA – AKO BISAYA, INC.'],
                    ['code' => 'PL -93',    'name' => '(093) AVE – ALLIANCE OF VOLUNTEER EDUCATORS'],
                    ['code' => 'PL -94',    'name' => '(094) METRO – MOVEMENT FOR ECONOMIC TRANSFORMATION AND RIGHTEOUS OPPORTUNITIES'],
                    ['code' => 'PL -95',    'name' => '(095) AASENSO – ATING AGAPAY SENTRONG SAMAHAN NG MGA OBRERO, INC.'],
                    ['code' => 'PL -96',    'name' => '(096) ALONA – ALLIANCE OF ORGANIZATIONS, NETWORKS AND ASSOCIATIONS OF THE PHILIPPINES'],
                    ['code' => 'PL -97',    'name' => '(097) TRICAP – TRIBAL COMMUNITIES ASSOCIATION OF THE PHILIPPINES'],
                    ['code' => 'PL -98',    'name' => '(098) BANAT – BARANGAY NATIN'],
                    ['code' => 'PL -99',    'name' => '(099) TINGOG SINIRANGAN – TINGOG SINIRANGAN'],
                    ['code' => 'PL -100',    'name' => '(100) MANILA TEACHERS’ – MANILA TEACHERS’ SAVINGS AND LOAN ASSOCIATION, INC.'],
                    ['code' => 'PL -101',    'name' => '(101) ACT-CIS – ANTI-CRIME AND TERRORISM COMMUNITY INVOLVEMENT AND SUPPORT, INC.'],
                    ['code' => 'PL -103',    'name' => '(103) APPEND – APPEND INC.'],
                    ['code' => 'PL -104',    'name' => '(104) CONSLA – CONFEDERATION OF NON-STOCK SAVINGS AND LOAN ASSOCIATIONS, INC.'],
                    ['code' => 'PL -105',    'name' => '(105) KMM – KAISAHAN NG MGA MALILIIT NA MAGSASAKA'],
                    ['code' => 'PL -108',    'name' => '(108) ABAKADA – ABAKADA GURO'],
                    ['code' => 'PL -109',    'name' => '(109) KALINGA – KALINGA – ADVOCACY FOR SOCIAL EMPOWERMENT AND NATION-BUILDING THROUGH EASING POVERTY, INC.'],
                    ['code' => 'PL -110',    'name' => '(110) MARVELOUS TAYO – NOBLE ADVANCEMENT OF MARVELOUS PEOPLE OF THE PHILIPPINES, INC.'],
                    ['code' => 'PL -112',    'name' => '(112) AAMBIS-OWA – ANG ASOSASYON SANG MANGUNGUMA NGA BISAYA-OWA MANGUNGUMA, INC'],
                    ['code' => 'PL -113',    'name' => '(113) TINDERONG PINOY – TINDERONG PINOY PARTY'],
                    ['code' => 'PL -114',    'name' => '(114) AGRI – AGRI-AGRA NA REPORMA PARA SA MAGSASAKA NG PILIPINAS MOVEMENT'],
                    ['code' => 'PL -115',    'name' => '(115) AGAP – AGRICULTURAL SECTOR ALLIANCE OF THE PHILIPPINES'],
                    ['code' => 'PL -116',    'name' => '(116) ACTS-OFW – ACTS OVERSEAS FILIPINO WORKERS COALITION OF ORGANIZATIONS'],
                    ['code' => 'PL -117',    'name' => '(117) FICTAP – FEDERATION OF INTERNATION CABLE TV AND TELECOMMUNICATIONS ASSOCIATIONS OF THE PHILIPPINES'],
                    ['code' => 'PL -121',    'name' => '(121) SAMAKO – SANDIGAN NG MGA MANGGAGAWA SA KONSTRUKSIYON'],
                    ['code' => 'PL -122',    'name' => '(122) 1PACMAN – ONE PATRIOTIC COALITION OF MARGINALIZED NATIONALS'],
                    ['code' => 'PL -124',    'name' => '(124) ABAMIN – ABANTE MINDANAO, INC.'],
                    ['code' => 'PL -126',    'name' => '(126) PLM – PARTIDO LAKAS NG MASA'],
                    ['code' => 'PL -127',    'name' => '(127) AWAKE – AWARENESS OF KEEPERS OF THE ENVIRONMENT, INC.'],
                    ['code' => 'PL -130',    'name' => '(130) SENIOR CITIZENS – COALITION OF ASSOCIATION OF SENIOR CITIZENS IN THE PHILIPPINES, INC.'],
                    ['code' => 'PL -131',    'name' => '(131) A TEACHER – ADVOCACY FOR TEACHER EMPOWERMENT THROUGH ACTION COOPERATION AND HARMONY TOWARDS EDUCATIONAL REFORM'],
                    ['code' => 'PL -132',    'name' => '(132) GP – GALING SA PUSO PARTY'],
                    ['code' => 'PL -133',    'name' => '(133) 1-APTO – ALLIANCE OF PUBLIC TRANSPORT ORGANIZATION INC.'],
                    ['code' => 'PL -134',    'name' => '(134) 1-AHAPO – ONE ADVOCACY FOR HEALTH, PROGRESS AND OPPORTUNITY'],
                    ['code' => 'PL -136',    'name' => '(136) ANG KABUHAYAN – ANG KABUHAYAN'],
                    ['code' => 'PL -137',    'name' => '(137) YACAP –YOU AGAINST CORRUPTION AND POVERTY'],
                    ['code' => 'PL -138',    'name' => '(138) MAGDALO – MAGDALO PARA SA PILIPINO'],
                    ['code' => 'PL -139',    'name' => '(139) ANUPA – ALLIANCE OF NATIONAL URBAN POOR ORGANIZATION ASSEMBLY, INC.'],
                    ['code' => 'PL -140',    'name' => '(140) 1-CARE – 1ST CONSUMERS ALLIANCE FOR RURAL ENERGY, INC.'],
                    ['code' => 'PL -141',    'name' => '(141) AKO BICOL – AKO BICOL POLITICAL PARTY'],
                    ['code' => 'PL -142',    'name' => '(142) COOP-NATCOO – COOPERATIVE NATCCO NETWORK'],
                    ['code' => 'PL -143',    'name' => '(143) MAYPAGASA – KILUSANG MAYPAGASA'],
                    ['code' => 'PL -144',    'name' => '(144) ATING KOOP – ADHIKAING TINAGUYOD NG KOOPERATIBA'],
                    ['code' => 'PL -147',    'name' => '(147) ALENG ENTREP – ASSOCIATION OF LADY ENTREPRENEURS'],
                    ['code' => 'PL -148',    'name' => '(148) AANGAT TAYO – AANGAT TAYO'],
                    ['code' => 'PL -149',    'name' => '(149) KABALIKAT – KABALIKAT NG NAGKAKAISANG MANILEÑO'],
                    ['code' => 'PL -150',    'name' => '(150) BHW – BARANGAY HEALTH WELLNESS'],
                    ['code' => 'PL -151',    'name' => '(151) RECOBODA – RURAL ELECTRIC CONSUMERS AND BENEFICIARIES OF DEVELOPMENT AND ADVANCEMENT, INC.'],
                    ['code' => 'PL -152',    'name' => '(152) AKO PADAYON – AKO PADAYON PILIPINO'],
                    ['code' => 'PL -153',    'name' => '(153) AMIN – ANAK MINDANAO'],
                    ['code' => 'PL -155',    'name' => '(155) – ITO ANG TAMA – TANGGOL MARALITA'],
                    ['code' => 'PL -156',    'name' => '(156) 1 UTAP BICOL – ONE UNIFIED TRANSPORT ALLIANCE OF THE PHILIPPINES-BICOL REGION'],
                    ['code' => 'PL -157',    'name' => '(157) DUTERTE YOUTH – DUTY TO ENERGIZE THE REPUBLIC THROUGH THE ENLIGHTENMENT OF THE YOUTH SECTORAL PARTY-LIST ORGANIZATION'],
                    ['code' => 'PL -158',    'name' => '(158) BUTIL – BUTIL FARMERS PARTY'],
                    ['code' => 'PL -163',    'name' => '(163) ABANG LINGKOD – ABANG LINGKOD, INC.'],
                    ['code' => 'PL -164',    'name' => '(164) AGBIAG! – AGBIAG! TIMPUYOG ILOCANO, INC.'],
                    ['code' => 'PL -166',    'name' => '(166) TUCP – TRADE UNION CONGRESS PARTY'],
                    ['code' => 'PL -168',    'name' => '(168) FFF – FILIPINO FAMILY PARTY'],
                    ['code' => 'PL -169',    'name' => '(169) WOW PILIPINAS – WOW PILIPINAS MOVEMENT'],
                    ['code' => 'PL -170',    'name' => '(170) SAGIP – SOCIAL AMELIORATION AND GENUINE INTERVENTION ON POVERTY'],
                    ['code' => 'PL -171',    'name' => '(171) DIWA – DEMOCRATIC INDEPENDENT WORKERS’ ASSOCIATION'],
                    ['code' => 'PL -172',    'name' => '(172) PHILRECA – PHILIPPINE RURAL ELECTRIC COOPERATIVES ASSOCIATION, INC.'],
                    ['code' => 'PL -173',    'name' => '(173) 1P – ONE PHILIPPINES'],
                    ['code' => 'PL -175',    'name' => '(175) PBB – PARTIDO NG BAYAN ANG BIDA'],
                    ['code' => 'PL -176',    'name' => '(176) LAANG KAWAL – LAANG KAWAL NG PILIPINAS'],
                    ['code' => 'PL -177',    'name' => '(177) 1AAAP – 1 ALLIANCE ADVOCATING AUTONOMY PARTY'],
                    ['code' => 'PL -180',    'name' => '(180) GRECON – GRAINS RETAILERS’ CONFEDERATION OF THE PHILIPPINES, INC'],
                    ['code' => 'PL -181',    'name' => '(181) AA-KASOSYO PARTY – KASOSYO PRODUCER-CONSUMER EXCHANGE ASSOCIATION INC.'],
                ],
            ],
            [
                'position' => 'Governor',
                'candidates' => [
                    ['code' => 'ACOSTA',    'name' => 'ACOSTA, JUAN'],
                    ['code' => 'LAZARO',    'name' => 'LAZARO, MELCHOR'],
                    ['code' => 'RIVERA-2',  'name' => 'RIVERA, BAYANI'],
                    ['code' => 'WARD',      'name' => 'WARD, LIBERATO'],
                ],
            ],
            [
                'position' => 'Vice-Governor',
                'candidates' => [
                    ['code' => 'BALLESTEROS',   'name' => 'BALLESTEROS, RIZA'],
                    ['code' => 'DOMINGUEZ',     'name' => 'DOMINGUEZ, JESUS'],
                    ['code' => 'MORENO',        'name' => 'MORENO, PETER'],
                    ['code' => 'NAVARRO-1',       'name' => 'NAVARRO, CHERRY'],
                    ['code' => 'SOLIS',         'name' => 'SOLIS, ROMEL'],
                ],
            ],
            [
                'position' => 'Board Member',
                'candidates' => [
                    ['code' => 'BRIONES',   'name' => 'BRIONES, JEJOMAR'],
                    ['code' => 'CANLAS',    'name' => 'CANLAS, WARREN'],
                    ['code' => 'FERRER',    'name' => 'FERRER, ARNEL'],
                    ['code' => 'GOMEZ',     'name' => 'GOMEZ, RESTITUTO'],
                    ['code' => 'KOLLINS',   'name' => 'KOLLINS, EFREN'],
                    ['code' => 'LEWIS',     'name' => 'LEWIS, ANGELITA'],
                    ['code' => 'MUNOZ',     'name' => 'MUNOZ, TONY'],
                    ['code' => 'ONG-2',       'name' => 'ONG, YOLANDA'],
                    ['code' => 'RODEL',     'name' => 'RODEL, ROSS'],
                    ['code' => 'WONG',      'name' => 'WONG, CESAR'],
                ],
            ],
            [
                'position' => 'Congressman',
                'candidates' => [
                    ['code' => 'ESGUERRA',  'name' => 'ESGUERRA, FLORDELIZA'],
                    ['code' => 'PENA',      'name' => 'PENA, BERTO'],
                    ['code' => 'TORRES',    'name' => 'TORRES, ALBERTO'],
                ],
            ],
            [
                'position' => 'Mayor',
                'candidates' => [
                    ['code' => 'BANAAG',    'name' => 'BANAAG, MAURICE'],
                    ['code' => 'DIMALANTA',    'name' => 'DIMALANTA, JEAN'],
                    ['code' => 'SEGUNDO',    'name' => 'SEGUNDO, FRANCO'],
                ],
            ],
            [
                'position' => 'Vice-Mayor',
                'candidates' => [
                    ['code' => 'ESCALANTE',    'name' => 'ESCALANTE, CORAZON'],
                    ['code' => 'MUNSAYAC',    'name' => 'MUNSAYAC, ARTHUR'],
                    ['code' => 'ROSALES',    'name' => 'ROSALES, MARISA'],
                ],
            ],
            [
                'position' => 'Councilor',
                'candidates' => [
                    ['code' => 'AGUILAR-2',    'name' => 'AGUILAR, ADIL'],
                    ['code' => 'AUGUSTIN',    'name' => 'AUGUSTIN, DEVEN'],
                    ['code' => 'BORJE',    'name' => 'BORJE, ANDONG'],
                    ['code' => 'CEREZO',    'name' => 'CEREZO, ANGKIN'],
                    ['code' => 'DULCE',    'name' => 'DULCE, COCO'],
                    ['code' => 'ENRICO',    'name' => 'ENRICO, PAULEEN'],
                    ['code' => 'GARCIA',    'name' => 'GARCIA, EDGARDO'],
                    ['code' => 'LIMJOCO',    'name' => 'LIMJOCO, PETER'],
                    ['code' => 'MARASIGAN',    'name' => 'MARASIGAN, BETH'],
                    ['code' => 'MENDOZA',    'name' => 'MENDOZA, MILAGROS'],
                    ['code' => 'NAVARRO-2',    'name' => 'NAVARRO, ALBERT'],
                    ['code' => 'OCAMPO',    'name' => 'OCAMPO, RODOLFO'],
                    ['code' => 'RAMOS',    'name' => 'RAMOS, RUBEN'],
                    ['code' => 'SALAZAR',    'name' => 'SALAZAR, PONCE'],
                    ['code' => 'VILLANUEVA',    'name' => 'VILLANUEVA, BIENVENIDO'],
                ],
            ],
        ];

        foreach ($positions_array as $position_record) {
            $position = Position::withName($position_record['position'])->first();
            foreach ($position_record['candidates'] as $candidate_record) {
                Candidate::create($position, $candidate_record);
            }
        }
    }
}
