<?php

use Illuminate\Database\Seeder;
use LBHurtado\Ballot\Models\{
    Candidate, Position
};

class CandidateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $positions_array = [
            [
                'position' => 'President',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'BELLEZA', 'name' => 'BELLEZA, DARIN'],
                    ['sequence' => 2, 'code' => 'BAUTISTA-1', 'name' => 'BAUTISTA, TERRENCE'],
                    ['sequence' => 3, 'code' => 'BAUTISTA-2', 'name' => 'BAUTISTA, VIRGINIA'],
                    ['sequence' => 4, 'code' => 'BUENAFLOR', 'name' => 'BUENAFLOR, MARTIN'],
                    ['sequence' => 5, 'code' => 'NATIVIDAD', 'name' => 'NATIVIDAD, EVA'],
                    ['sequence' => 6, 'code' => 'ROBLES', 'name' => 'ROBLES, DENNIS'],
                ],
            ],
            [
                'position' => 'Vice-President',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'ISIGANI', 'name' => 'ISIGANI, GENER'],
                    ['sequence' => 2, 'code' => 'JIMENEZ', 'name' => 'JIMENEZ, HOMOBONO'],
                    ['sequence' => 3, 'code' => 'RIVERA-1', 'name' => 'RIVERA, JOSELITO'],
                    ['sequence' => 4, 'code' => 'VILORIA', 'name' => 'VILORIA, MARY']
                ],
            ],
            [
                'position' => 'Senator',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'ABEJO', 'name' => 'ABEJO, VANGIE'],
                    ['sequence' => 2, 'code' => 'AFUANG', 'name' => 'AFUANG, ABNER'],
                    ['sequence' => 3, 'code' => 'AGUILAR-1', 'name' => 'AGUILAR, FREDDIE'],
                    ['sequence' => 4, 'code' => 'ALBANI', 'name' => 'ALBANI, SHARIFF'],
                    ['sequence' => 5, 'code' => 'ALEJANO', 'name' => 'ALEJANO, GARY'],
                    ['sequence' => 6, 'code' => 'ALFAJORA', 'name' => 'ALFAJORA, RICHARD'],
                    ['sequence' => 7, 'code' => 'ALUNAN', 'name' => 'ALUNAN, RAFFY'],
                    ['sequence' => 8, 'code' => 'ANGARA', 'name' => 'ANGARA, EDGARDO SONNY'],
                    ['sequence' => 9, 'code' => 'AQUINO', 'name' => 'AQUINO, BENIGNO BAM'],
                    ['sequence' => 10, 'code' => 'ARCEGA', 'name' => 'ARCEGA, GERALD'],
                    ['sequence' => 11, 'code' => 'ARELLANO', 'name' => 'ARELLANO, ERNESTO'],
                    ['sequence' => 12, 'code' => 'ARIAS', 'name' => 'ARIAS, MARCELINO'],
                    ['sequence' => 13, 'code' => 'AUSTRIA', 'name' => 'AUSTRIA, BERNARD'],
                    ['sequence' => 14, 'code' => 'BALDEVARONA', 'name' => 'BALDEVARONA, BALDE'],
                    ['sequence' => 15, 'code' => 'BINAY', 'name' => 'BINAY, NANCY'],
                    ['sequence' => 16, 'code' => 'BONG REVILLA', 'name' => 'BONG REVILLA, RAMON JR'],
                    ['sequence' => 17, 'code' => 'CACERES', 'name' => 'CACERES, JESUS'],
                    ['sequence' => 18, 'code' => 'CASIÑO', 'name' => 'CASIÑO, TOTI'],
                    ['sequence' => 19, 'code' => 'CAYETANO', 'name' => 'CAYETANO, PIA'],
                    ['sequence' => 20, 'code' => 'CHAVEZ', 'name' => 'CHAVEZ, MELCHOR'],
                    ['sequence' => 21, 'code' => 'CHONG', 'name' => 'CHONG, GLENN'],
                    ['sequence' => 22, 'code' => 'COLMENARES', 'name' => 'COLMENARES, NERI'],
                    ['sequence' => 23, 'code' => 'DE GUZMAN', 'name' => 'DE GUZMAN, KA LEODY'],
                    ['sequence' => 24, 'code' => 'DELA ROSA', 'name' => 'DELA ROSA, BATO'],
                    ['sequence' => 25, 'code' => 'DIOKNO', 'name' => 'DIOKNO, CHEL'],
                    ['sequence' => 26, 'code' => 'EJERCITO', 'name' => 'EJERCITO, ESTRADA JV'],
                    ['sequence' => 27, 'code' => 'ENRILE', 'name' => 'ENRILE, JUAN PONCE'],
                    ['sequence' => 28, 'code' => 'ESCUDERO', 'name' => 'ESCUDERO, AGNES'],
                    ['sequence' => 29, 'code' => 'ESTRADA', 'name' => 'ESTRADA, JINGGOY'],
                    ['sequence' => 30, 'code' => 'FRANCISCO', 'name' => 'FRANCISCO, ELMER'],
                    ['sequence' => 31, 'code' => 'GADDI', 'name' => 'GADDI, CHARLIE'],
                    ['sequence' => 32, 'code' => 'GADON', 'name' => 'GADON, LARRY'],
                    ['sequence' => 33, 'code' => 'GENEROSO', 'name' => 'GENEROSO, GEN PEDERALISMO'],
                    ['sequence' => 34, 'code' => 'GO', 'name' => 'GO, BONG GO'],
                    ['sequence' => 35, 'code' => 'GUIGAYUMA', 'name' => 'GUIGAYUMA, JUNBERT'],
                    ['sequence' => 36, 'code' => 'GUTOC', 'name' => 'GUTOC, SAMIRA'],
                    ['sequence' => 37, 'code' => 'HILBAY', 'name' => 'HILBAY, PILO'],
                    ['sequence' => 38, 'code' => 'JANGAO', 'name' => 'JANGAO, BFG ABRAHAM'],
                    ['sequence' => 39, 'code' => 'JAVELLANA', 'name' => 'JAVELLANA, RJ'],
                    ['sequence' => 40, 'code' => 'LAPID', 'name' => 'LAPID, LITO'],
                    ['sequence' => 41, 'code' => 'MACALINTAL', 'name' => 'MACALINTAL, MACAROMY'],
                    ['sequence' => 42, 'code' => 'MALLILLIN', 'name' => 'MALLILLIN, EMILY'],
                    ['sequence' => 43, 'code' => 'MANGONDATO', 'name' => 'MANGONDATO, FAISAL'],
                    ['sequence' => 44, 'code' => 'MANGUDADATU', 'name' => 'MANGUDADATU, DONG'],
                    ['sequence' => 45, 'code' => 'MANICAD', 'name' => 'MANICAD, JIGGY'],
                    ['sequence' => 46, 'code' => 'MARCOS', 'name' => 'MARCOS, IMEE'],
                    ['sequence' => 47, 'code' => 'MATULA', 'name' => 'MATULA, JOSE SONNY'],
                    ['sequence' => 48, 'code' => 'MENIANO', 'name' => 'MENIANO, LUTHER'],
                    ['sequence' => 49, 'code' => 'MONTAÑO', 'name' => 'MONTAÑO, ALLAN'],
                    ['sequence' => 50, 'code' => 'NALLIW', 'name' => 'NALLIW, JOAN SHEELAH'],
                    ['sequence' => 51, 'code' => 'ONG-1', 'name' => 'ONG, DOC WILLIE'],
                    ['sequence' => 52, 'code' => 'OSMEÑA', 'name' => 'OSMEÑA, SERGE'],
                    ['sequence' => 53, 'code' => 'PADILLA', 'name' => 'PADILLA, DADO'],
                    ['sequence' => 54, 'code' => 'PIMENTEL', 'name' => 'PIMENTEL, KOKO'],
                    ['sequence' => 55, 'code' => 'POE', 'name' => 'POE, GRACE'],
                    ['sequence' => 56, 'code' => 'ROLEDA', 'name' => 'ROLEDA, DAN KAIBIGAN'],
                    ['sequence' => 57, 'code' => 'ROXAS', 'name' => 'ROXAS, MAR'],
                    ['sequence' => 58, 'code' => 'SAHIDULLA', 'name' => 'SAHIDULLA, LADY ANN'],
                    ['sequence' => 59, 'code' => 'TAÑADA', 'name' => 'TAÑADA, LORENZO ERIN TAPAT'],
                    ['sequence' => 60, 'code' => 'TOLENTINO', 'name' => 'TOLENTINO, FRANCIS'],
                    ['sequence' => 61, 'code' => 'VALDES', 'name' => 'VALDES, BUTCH'],
                    ['sequence' => 62, 'code' => 'VILLAR', 'name' => 'VILLAR, CYNTHIA'],
                ],
            ],
            [
                'position' => 'Party-List',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'PL -1', 'name' => '(001) BAYAN MUNA – BAYAN MUNA'],
                    ['sequence' => 2, 'code' => 'PL -2', 'name' => '(002) KABAYAN – KABALIKAT NG MAMAMAYAN'],
                    ['sequence' => 3, 'code' => 'PL -3', 'name' => '(003) MAGSASAKA – MAGKAKASAMA SA SAKAHAN, KAUNLARAN'],
                    ['sequence' => 4, 'code' => 'PL -4', 'name' => '(004) PEACE – PHILIPPINE EDUCATORS ALLIANCE FOR COMMUNITY EMPOWERMENT'],
                    ['sequence' => 5, 'code' => 'PL -6', 'name' => '(006) KONTRA BROWNOUT PARTYLIST – NATIONAL ASSOCIATION FOR ELECTRICITY CONSUMERS FOR REFORMS, INC'],
                    ['sequence' => 6, 'code' => 'PL -7', 'name' => '(007) OFW FAMILY – OFW FAMILY CLUB, INC'],
                    ['sequence' => 7, 'code' => 'PL -8', 'name' => '(008) 1-UTAK – 1-UNITED TRANSPORT KOALISYON'],
                    ['sequence' => 8, 'code' => 'PL -9', 'name' => '(009) KUSUG TAUSUG – KUSUG TAUSUG'],
                    ['sequence' => 9, 'code' => 'PL -10', 'name' => '(010) GLOBAL – GLOBAL WORKERS AND FAMILY FEDERATION, INC.'],
                    ['sequence' => 10, 'code' => 'PL -12', 'name' => '(012) ANG NARS – ANG NARS, INC.'],
                    ['sequence' => 11, 'code' => 'PL -14', 'name' => '(014) ANAKPAWIS – ANAKPAWIS'],
                    ['sequence' => 12, 'code' => 'PL -16', 'name' => '(016) CWS – CONSTRUCTION WORKERS’ SOLIDARITY'],
                    ['sequence' => 13, 'code' => 'PL -17', 'name' => '(017) PTA –  PARENTS TEACHERS ALLIANCE'],
                    ['sequence' => 14, 'code' => 'PL -18', 'name' => '(018) RAM – Rebolusyonaryong Alyansang Makabansa'],
                    ['sequence' => 15, 'code' => 'PL -20', 'name' => '(020) DUMPER PTDA – DUMPER PHILIPPINES TAXI DRIVERS ASSOCIATION, INC.'],
                    ['sequence' => 16, 'code' => 'PL -21', 'name' => '(021) LUNTIAN – LUNTIANG PILIPINAS PARTYLIST'],
                    ['sequence' => 17, 'code' => 'PL -22', 'name' => '(022) AKO BISDAK – AKO BISDAK-BISAYANG DAKO (AB-DB), INC.'],
                    ['sequence' => 18, 'code' => 'PL -23', 'name' => '(023) ASEAN – ACADEMICIANS, STUDENTS AND EDUCATORS ALLIANCE INC.'],
                    ['sequence' => 19, 'code' => 'PL -24', 'name' => '(024) APEC – ASSOCIATION OF PHILIPPINES ELECTRIC COOPERATIVES'],
                    ['sequence' => 20, 'code' => 'PL -26', 'name' => '(026) PBA – PUWERSA NG BAYANING ATLETA'],
                    ['sequence' => 21, 'code' => 'PL -27', 'name' => '(027) AMEPA OFW – AMEPA OFW ACCESS CENTER, INC.'],
                    ['sequence' => 22, 'code' => 'PL -29', 'name' => '(029) BAHAY – BAHAY PARA SA PAMILYANG PILIPINO, INC.'],
                    ['sequence' => 23, 'code' => 'PL -30', 'name' => '(030) PRAI – PHILIPPINE NATIONAL POLICE RETIREES ASSOCIATION, INC.'],
                    ['sequence' => 24, 'code' => 'PL -31', 'name' => '(031) JUAN MOVEMENT – JOINT UNION OF ACTIVE NATIONALIST FILIPINO MOVEMENT'],
                    ['sequence' => 25, 'code' => 'PL -32', 'name' => '(032) BUKLOD FILIPINO – PINAGBUKLOD NA FILIPINO PARA SA BAYAN'],
                    ['sequence' => 26, 'code' => 'PL -33', 'name' => '(033) CIBAC – CITIZENS’ BATTLE AGAINST CORRUPTION'],
                    ['sequence' => 27, 'code' => 'PL -35', 'name' => '(035) MURANG KURYENTE – MURANG KURYENTE PARTYLIST'],
                    ['sequence' => 28, 'code' => 'PL -36', 'name' => '(036) ANGKLA – ANGKLA: ANG PARTIDO NG MGA PILIPINONG MARINO, INC.'],
                    ['sequence' => 29, 'code' => 'PL -37', 'name' => '(037) GABRIELA – GABRIELA WOMEN’S APRTY'],
                    ['sequence' => 30, 'code' => 'PL -38', 'name' => '(038) AKO AN BISAYA – AKO AN BISAYA'],
                    ['sequence' => 31, 'code' => 'PL -39', 'name' => '(039) 1-LAMBAT – ISANG LAPIAN NG MANGINGISDA AT BAYAN TUNGO SA KAUNLARAN'],
                    ['sequence' => 32, 'code' => 'PL -42', 'name' => '(042) KABATAAN – KABATAAN PARTY LIST'],
                    ['sequence' => 33, 'code' => 'PL -43', 'name' => '(043) AN WARAY – AN WARAY'],
                    ['sequence' => 34, 'code' => 'PL -44', 'name' => '(044) SULONG DIGNIDAD – SULONG DIGNIDAD PARTY'],
                    ['sequence' => 35, 'code' => 'PL -46', 'name' => '(046) ALL-FISH – ALLIANCE OF PHILIPPINE FISHING FEDERATIONS, INC.'],
                    ['sequence' => 36, 'code' => 'PL -47', 'name' => '(047) ANAKLUSUGAN – ALAGAAN NATIN ATING KALUSUGAN'],
                    ['sequence' => 37, 'code' => 'PL -48', 'name' => '(048) TGP – TALINO AT GALING NG PINOY'],
                    ['sequence' => 38, 'code' => 'PL -49', 'name' => '(049) ABEKA – ABE KAPAMPANGAN (ABEKA) INC.'],
                    ['sequence' => 39, 'code' => 'PL -51', 'name' => '(051) AKMA-PTM – AKSYON MAGSASAKA-PARTIDO TINIG NG MASA (AKMA-PTM)'],
                    ['sequence' => 40, 'code' => 'PL -52', 'name' => '(052) ABS –ARTS BUSINESS AND SCIENCE PROFESSIONALS'],
                    ['sequence' => 41, 'code' => 'PL -53', 'name' => '(053) BH – BAGONG HENERASYON'],
                    ['sequence' => 42, 'code' => 'PL -54', 'name' => '(054) ANG PROBINSYANO – ALYANSA NG MGA MAMAMAYANG PROBINSYANO'],
                    ['sequence' => 43, 'code' => 'PL -55', 'name' => '(055) PM – PARTIDO MANGGAGAWA'],
                    ['sequence' => 44, 'code' => 'PL -58', 'name' => '(058) ANAC-IP – ANG NATIONAL COALITION OF INDIGENOUS PEOPLE ACTION NA! INC.'],
                    ['sequence' => 45, 'code' => 'PL -59', 'name' => '(059) SINAG – SINAG TUNGO SA KAUNLARAN'],
                    ['sequence' => 46, 'code' => 'PL -60', 'name' => '(060) PATROL – PUBLIC SAFETY ALLIANCE FOR TRANSFORMATION AND RULE OF LAW, INC.'],
                    ['sequence' => 47, 'code' => 'PL -63', 'name' => '(063) KOOP-KAMPI – KOOPERATIBA-KAPISANAN NG MAGSASAKA NG PILIPINAS'],
                    ['sequence' => 48, 'code' => 'PL -65', 'name' => '(065) UNIDO – UNION OF NATIONALISTIC DEMOCRATIC FILIPINO ORGANIZATION'],
                    ['sequence' => 49, 'code' => 'PL -67', 'name' => '(067) SBP – SERBISYO SA BAYAN APRTY'],
                    ['sequence' => 50, 'code' => 'PL -68', 'name' => '(068) PPP – PILIPINAS PARA SA PINOY'],
                    ['sequence' => 51, 'code' => 'PL -69', 'name' => '(069) INANG MAHAL – INA NA NAGMAMAHAL SA ANAK'],
                    ['sequence' => 52, 'code' => 'PL -71', 'name' => '(071) 1-ANG EDUKASYON – UNA ANG EDUKASYON'],
                    ['sequence' => 53, 'code' => 'PL -72', 'name' => '(072) KAMAIS – KAMAIS PILIPINAS (KAPATIRANG MAGMAMAIS NG PILIPINAS, INC.)'],
                    ['sequence' => 54, 'code' => 'PL -73', 'name' => '(073) ALIF – ANG LABAN NG INDIGINONG FILIPINO'],
                    ['sequence' => 55, 'code' => 'PL -74', 'name' => '(074) MATA – ANG MATA’Y ALAGAAN'],
                    ['sequence' => 56, 'code' => 'PL -75', 'name' => '(075) LPGMA – LPG MARKETERS ASSOCIATION INC.'],
                    ['sequence' => 57, 'code' => 'PL -76', 'name' => '(076) ABONO – ABONO'],
                    ['sequence' => 58, 'code' => 'PL -78', 'name' => '(078) AKO – AKO AYOKO SA BAWAL NA DROGA'],
                    ['sequence' => 59, 'code' => 'PL -79', 'name' => '(079) ABANTE PILIPINAS – AVID BUILDERS OF ACTIVE NATION’S CITIZENRY TOWARDS EMPOWERED PHILIPPINES'],
                    ['sequence' => 60, 'code' => 'PL -80', 'name' => '(080) MARINO – MARINO SAMAHAN NG MGA SEAMAN, INC.'],
                    ['sequence' => 61, 'code' => 'PL -82', 'name' => '(082) TAO MUNA – ANG TAO MUNA AT BAYAN'],
                    ['sequence' => 62, 'code' => 'PL -83', 'name' => '(083) ACT TEACHERS – ACT TEACHERS'],
                    ['sequence' => 63, 'code' => 'PL -84', 'name' => '(084) PEOPLE’S CHAMP – PEOPLE’S CHAMP GUARDIANS'],
                    ['sequence' => 64, 'code' => 'PL -86', 'name' => '(086) ALAY BUHAY – ALAY BUHAY COMMUNITY DEVELOPMENT FOUNDATION, INC.'],
                    ['sequence' => 65, 'code' => 'PL -87', 'name' => '(087) BUHAY – BUHAY HAYAAN YUMABONG'],
                    ['sequence' => 66, 'code' => 'PL -88', 'name' => '(088) AKBAYAN – AKBAYAN CITIZENS ACTION PARTY'],
                    ['sequence' => 67, 'code' => 'PL -89', 'name' => '(089) PARTIDO SANDUGO – PARTIDO SANDUGO'],
                    ['sequence' => 68, 'code' => 'PL -91', 'name' => '(091) PROBINSYANO AKO – PROBINSYANO AKO'],
                    ['sequence' => 69, 'code' => 'PL -92', 'name' => '(092) AKO BISAYA – AKO BISAYA, INC.'],
                    ['sequence' => 70, 'code' => 'PL -93', 'name' => '(093) AVE – ALLIANCE OF VOLUNTEER EDUCATORS'],
                    ['sequence' => 71, 'code' => 'PL -94', 'name' => '(094) METRO – MOVEMENT FOR ECONOMIC TRANSFORMATION AND RIGHTEOUS OPPORTUNITIES'],
                    ['sequence' => 72, 'code' => 'PL -95', 'name' => '(095) AASENSO – ATING AGAPAY SENTRONG SAMAHAN NG MGA OBRERO, INC.'],
                    ['sequence' => 73, 'code' => 'PL -96', 'name' => '(096) ALONA – ALLIANCE OF ORGANIZATIONS, NETWORKS AND ASSOCIATIONS OF THE PHILIPPINES'],
                    ['sequence' => 74, 'code' => 'PL -97', 'name' => '(097) TRICAP – TRIBAL COMMUNITIES ASSOCIATION OF THE PHILIPPINES'],
                    ['sequence' => 75, 'code' => 'PL -98', 'name' => '(098) BANAT – BARANGAY NATIN'],
                    ['sequence' => 76, 'code' => 'PL -99', 'name' => '(099) TINGOG SINIRANGAN – TINGOG SINIRANGAN'],
                    ['sequence' => 77, 'code' => 'PL -100', 'name' => '(100) MANILA TEACHERS’ – MANILA TEACHERS’ SAVINGS AND LOAN ASSOCIATION, INC.'],
                    ['sequence' => 78, 'code' => 'PL -101', 'name' => '(101) ACT-CIS – ANTI-CRIME AND TERRORISM COMMUNITY INVOLVEMENT AND SUPPORT, INC.'],
                    ['sequence' => 79, 'code' => 'PL -103', 'name' => '(103) APPEND – APPEND INC.'],
                    ['sequence' => 80, 'code' => 'PL -104', 'name' => '(104) CONSLA – CONFEDERATION OF NON-STOCK SAVINGS AND LOAN ASSOCIATIONS, INC.'],
                    ['sequence' => 81, 'code' => 'PL -105', 'name' => '(105) KMM – KAISAHAN NG MGA MALILIIT NA MAGSASAKA'],
                    ['sequence' => 82, 'code' => 'PL -108', 'name' => '(108) ABAKADA – ABAKADA GURO'],
                    ['sequence' => 83, 'code' => 'PL -109', 'name' => '(109) KALINGA – KALINGA – ADVOCACY FOR SOCIAL EMPOWERMENT AND NATION-BUILDING THROUGH EASING POVERTY, INC.'],
                    ['sequence' => 84, 'code' => 'PL -110', 'name' => '(110) MARVELOUS TAYO – NOBLE ADVANCEMENT OF MARVELOUS PEOPLE OF THE PHILIPPINES, INC.'],
                    ['sequence' => 85, 'code' => 'PL -112', 'name' => '(112) AAMBIS-OWA – ANG ASOSASYON SANG MANGUNGUMA NGA BISAYA-OWA MANGUNGUMA, INC'],
                    ['sequence' => 86, 'code' => 'PL -113', 'name' => '(113) TINDERONG PINOY – TINDERONG PINOY PARTY'],
                    ['sequence' => 87, 'code' => 'PL -114', 'name' => '(114) AGRI – AGRI-AGRA NA REPORMA PARA SA MAGSASAKA NG PILIPINAS MOVEMENT'],
                    ['sequence' => 88, 'code' => 'PL -115', 'name' => '(115) AGAP – AGRICULTURAL SECTOR ALLIANCE OF THE PHILIPPINES'],
                    ['sequence' => 89, 'code' => 'PL -116', 'name' => '(116) ACTS-OFW – ACTS OVERSEAS FILIPINO WORKERS COALITION OF ORGANIZATIONS'],
                    ['sequence' => 90, 'code' => 'PL -117', 'name' => '(117) FICTAP – FEDERATION OF INTERNATION CABLE TV AND TELECOMMUNICATIONS ASSOCIATIONS OF THE PHILIPPINES'],
                    ['sequence' => 91, 'code' => 'PL -121', 'name' => '(121) SAMAKO – SANDIGAN NG MGA MANGGAGAWA SA KONSTRUKSIYON'],
                    ['sequence' => 92, 'code' => 'PL -122', 'name' => '(122) 1PACMAN – ONE PATRIOTIC COALITION OF MARGINALIZED NATIONALS'],
                    ['sequence' => 93, 'code' => 'PL -124', 'name' => '(124) ABAMIN – ABANTE MINDANAO, INC.'],
                    ['sequence' => 94, 'code' => 'PL -126', 'name' => '(126) PLM – PARTIDO LAKAS NG MASA'],
                    ['sequence' => 95, 'code' => 'PL -127', 'name' => '(127) AWAKE – AWARENESS OF KEEPERS OF THE ENVIRONMENT, INC.'],
                    ['sequence' => 96, 'code' => 'PL -130', 'name' => '(130) SENIOR CITIZENS – COALITION OF ASSOCIATION OF SENIOR CITIZENS IN THE PHILIPPINES, INC.'],
                    ['sequence' => 97, 'code' => 'PL -131', 'name' => '(131) A TEACHER – ADVOCACY FOR TEACHER EMPOWERMENT THROUGH ACTION COOPERATION AND HARMONY TOWARDS EDUCATIONAL REFORM'],
                    ['sequence' => 98, 'code' => 'PL -132', 'name' => '(132) GP – GALING SA PUSO PARTY'],
                    ['sequence' => 99, 'code' => 'PL -133', 'name' => '(133) 1-APTO – ALLIANCE OF PUBLIC TRANSPORT ORGANIZATION INC.'],
                    ['sequence' => 100, 'code' => 'PL -134', 'name' => '(134) 1-AHAPO – ONE ADVOCACY FOR HEALTH, PROGRESS AND OPPORTUNITY'],
                    ['sequence' => 101, 'code' => 'PL -136', 'name' => '(136) ANG KABUHAYAN – ANG KABUHAYAN'],
                    ['sequence' => 102, 'code' => 'PL -137', 'name' => '(137) YACAP –YOU AGAINST CORRUPTION AND POVERTY'],
                    ['sequence' => 103, 'code' => 'PL -138', 'name' => '(138) MAGDALO – MAGDALO PARA SA PILIPINO'],
                    ['sequence' => 104, 'code' => 'PL -139', 'name' => '(139) ANUPA – ALLIANCE OF NATIONAL URBAN POOR ORGANIZATION ASSEMBLY, INC.'],
                    ['sequence' => 105, 'code' => 'PL -140', 'name' => '(140) 1-CARE – 1ST CONSUMERS ALLIANCE FOR RURAL ENERGY, INC.'],
                    ['sequence' => 106, 'code' => 'PL -141', 'name' => '(141) AKO BICOL – AKO BICOL POLITICAL PARTY'],
                    ['sequence' => 107, 'code' => 'PL -142', 'name' => '(142) COOP-NATCOO – COOPERATIVE NATCCO NETWORK'],
                    ['sequence' => 108, 'code' => 'PL -143', 'name' => '(143) MAYPAGASA – KILUSANG MAYPAGASA'],
                    ['sequence' => 109, 'code' => 'PL -144', 'name' => '(144) ATING KOOP – ADHIKAING TINAGUYOD NG KOOPERATIBA'],
                    ['sequence' => 110, 'code' => 'PL -147', 'name' => '(147) ALENG ENTREP – ASSOCIATION OF LADY ENTREPRENEURS'],
                    ['sequence' => 111, 'code' => 'PL -148', 'name' => '(148) AANGAT TAYO – AANGAT TAYO'],
                    ['sequence' => 112, 'code' => 'PL -149', 'name' => '(149) KABALIKAT – KABALIKAT NG NAGKAKAISANG MANILEÑO'],
                    ['sequence' => 113, 'code' => 'PL -150', 'name' => '(150) BHW – BARANGAY HEALTH WELLNESS'],
                    ['sequence' => 114, 'code' => 'PL -151', 'name' => '(151) RECOBODA – RURAL ELECTRIC CONSUMERS AND BENEFICIARIES OF DEVELOPMENT AND ADVANCEMENT, INC.'],
                    ['sequence' => 115, 'code' => 'PL -152', 'name' => '(152) AKO PADAYON – AKO PADAYON PILIPINO'],
                    ['sequence' => 116, 'code' => 'PL -153', 'name' => '(153) AMIN – ANAK MINDANAO'],
                    ['sequence' => 117, 'code' => 'PL -155', 'name' => '(155) – ITO ANG TAMA – TANGGOL MARALITA'],
                    ['sequence' => 118, 'code' => 'PL -156', 'name' => '(156) 1 UTAP BICOL – ONE UNIFIED TRANSPORT ALLIANCE OF THE PHILIPPINES-BICOL REGION'],
                    ['sequence' => 119, 'code' => 'PL -157', 'name' => '(157) DUTERTE YOUTH – DUTY TO ENERGIZE THE REPUBLIC THROUGH THE ENLIGHTENMENT OF THE YOUTH SECTORAL PARTY-LIST ORGANIZATION'],
                    ['sequence' => 120, 'code' => 'PL -158', 'name' => '(158) BUTIL – BUTIL FARMERS PARTY'],
                    ['sequence' => 121, 'code' => 'PL -163', 'name' => '(163) ABANG LINGKOD – ABANG LINGKOD, INC.'],
                    ['sequence' => 122, 'code' => 'PL -164', 'name' => '(164) AGBIAG! – AGBIAG! TIMPUYOG ILOCANO, INC.'],
                    ['sequence' => 123, 'code' => 'PL -166', 'name' => '(166) TUCP – TRADE UNION CONGRESS PARTY'],
                    ['sequence' => 124, 'code' => 'PL -168', 'name' => '(168) FFF – FILIPINO FAMILY PARTY'],
                    ['sequence' => 125, 'code' => 'PL -169', 'name' => '(169) WOW PILIPINAS – WOW PILIPINAS MOVEMENT'],
                    ['sequence' => 126, 'code' => 'PL -170', 'name' => '(170) SAGIP – SOCIAL AMELIORATION AND GENUINE INTERVENTION ON POVERTY'],
                    ['sequence' => 127, 'code' => 'PL -171', 'name' => '(171) DIWA – DEMOCRATIC INDEPENDENT WORKERS’ ASSOCIATION'],
                    ['sequence' => 128, 'code' => 'PL -172', 'name' => '(172) PHILRECA – PHILIPPINE RURAL ELECTRIC COOPERATIVES ASSOCIATION, INC.'],
                    ['sequence' => 129, 'code' => 'PL -173', 'name' => '(173) 1P – ONE PHILIPPINES'],
                    ['sequence' => 130, 'code' => 'PL -175', 'name' => '(175) PBB – PARTIDO NG BAYAN ANG BIDA'],
                    ['sequence' => 131, 'code' => 'PL -176', 'name' => '(176) LAANG KAWAL – LAANG KAWAL NG PILIPINAS'],
                    ['sequence' => 132, 'code' => 'PL -177', 'name' => '(177) 1AAAP – 1 ALLIANCE ADVOCATING AUTONOMY PARTY'],
                    ['sequence' => 133, 'code' => 'PL -180', 'name' => '(180) GRECON – GRAINS RETAILERS’ CONFEDERATION OF THE PHILIPPINES, INC'],
                    ['sequence' => 134, 'code' => 'PL -181', 'name' => '(181) AA-KASOSYO PARTY – KASOSYO PRODUCER-CONSUMER EXCHANGE ASSOCIATION INC.'],
                ],
            ],
            [
                'position' => 'Governor',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'ACOSTA', 'name' => 'ACOSTA, JUAN'],
                    ['sequence' => 2, 'code' => 'LAZARO', 'name' => 'LAZARO, MELCHOR'],
                    ['sequence' => 3, 'code' => 'RIVERA-2', 'name' => 'RIVERA, BAYANI'],
                    ['sequence' => 4, 'code' => 'WARD', 'name' => 'WARD, LIBERATO'],
                ],
            ],
            [
                'position' => 'Vice-Governor',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'BALLESTEROS', 'name' => 'BALLESTEROS, RIZA'],
                    ['sequence' => 2, 'code' => 'DOMINGUEZ', 'name' => 'DOMINGUEZ, JESUS'],
                    ['sequence' => 3, 'code' => 'MORENO', 'name' => 'MORENO, PETER'],
                    ['sequence' => 4, 'code' => 'NAVARRO-1', 'name' => 'NAVARRO, CHERRY'],
                    ['sequence' => 5, 'code' => 'SOLIS', 'name' => 'SOLIS, ROMEL'],
                ],
            ],
            [
                'position' => 'Board Member',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'BRIONES', 'name' => 'BRIONES, JEJOMAR'],
                    ['sequence' => 2, 'code' => 'CANLAS', 'name' => 'CANLAS, WARREN'],
                    ['sequence' => 3, 'code' => 'FERRER', 'name' => 'FERRER, ARNEL'],
                    ['sequence' => 4, 'code' => 'GOMEZ', 'name' => 'GOMEZ, RESTITUTO'],
                    ['sequence' => 5, 'code' => 'KOLLINS', 'name' => 'KOLLINS, EFREN'],
                    ['sequence' => 6, 'code' => 'LEWIS', 'name' => 'LEWIS, ANGELITA'],
                    ['sequence' => 7, 'code' => 'MUNOZ', 'name' => 'MUNOZ, TONY'],
                    ['sequence' => 8, 'code' => 'ONG-2', 'name' => 'ONG, YOLANDA'],
                    ['sequence' => 9, 'code' => 'RODEL', 'name' => 'RODEL, ROSS'],
                    ['sequence' => 10, 'code' => 'WONG', 'name' => 'WONG, CESAR'],
                ],
            ],
            [
                'position' => 'Congressman',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'ESGUERRA', 'name' => 'ESGUERRA, FLORDELIZA'],
                    ['sequence' => 2, 'code' => 'PENA', 'name' => 'PENA, BERTO'],
                    ['sequence' => 3, 'code' => 'TORRES', 'name' => 'TORRES, ALBERTO'],
                ],
            ],
            [
                'position' => 'Mayor',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'BANAAG', 'name' => 'BANAAG, MAURICE'],
                    ['sequence' => 2, 'code' => 'DIMALANTA', 'name' => 'DIMALANTA, JEAN'],
                    ['sequence' => 3, 'code' => 'SEGUNDO', 'name' => 'SEGUNDO, FRANCO'],
                ],
            ],
            [
                'position' => 'Vice-Mayor',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'ESCALANTE', 'name' => 'ESCALANTE, CORAZON'],
                    ['sequence' => 2, 'code' => 'MUNSAYAC', 'name' => 'MUNSAYAC, ARTHUR'],
                    ['sequence' => 3, 'code' => 'ROSALES', 'name' => 'ROSALES, MARISA'],
                ],
            ],
            [
                'position' => 'Councilor',
                'candidates' => [
                    ['sequence' => 1, 'code' => 'AGUILAR-2', 'name' => 'AGUILAR, ADIL'],
                    ['sequence' => 2, 'code' => 'AUGUSTIN', 'name' => 'AUGUSTIN, DEVEN'],
                    ['sequence' => 3, 'code' => 'BORJE', 'name' => 'BORJE, ANDONG'],
                    ['sequence' => 4, 'code' => 'CEREZO', 'name' => 'CEREZO, ANGKIN'],
                    ['sequence' => 5, 'code' => 'DULCE', 'name' => 'DULCE, COCO'],
                    ['sequence' => 6, 'code' => 'ENRICO', 'name' => 'ENRICO, PAULEEN'],
                    ['sequence' => 7, 'code' => 'GARCIA', 'name' => 'GARCIA, EDGARDO'],
                    ['sequence' => 8, 'code' => 'LIMJOCO', 'name' => 'LIMJOCO, PETER'],
                    ['sequence' => 9, 'code' => 'MARASIGAN', 'name' => 'MARASIGAN, BETH'],
                    ['sequence' => 10, 'code' => 'MENDOZA', 'name' => 'MENDOZA, MILAGROS'],
                    ['sequence' => 11, 'code' => 'NAVARRO-2', 'name' => 'NAVARRO, ALBERT'],
                    ['sequence' => 12, 'code' => 'OCAMPO', 'name' => 'OCAMPO, RODOLFO'],
                    ['sequence' => 13, 'code' => 'RAMOS', 'name' => 'RAMOS, RUBEN'],
                    ['sequence' => 14, 'code' => 'SALAZAR', 'name' => 'SALAZAR, PONCE'],
                    ['sequence' => 15, 'code' => 'VILLANUEVA', 'name' => 'VILLANUEVA, BIENVENIDO'],
                ],
            ],
        ];

        foreach ($positions_array as $position_record) {
            $position = Position::withName($position_record['position'])->first();
            foreach ($position_record['candidates'] as $candidate_record) {
                Candidate::create($position, $candidate_record);
            }
        }
    }
}
